// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgukCNEIdHXJ1CxqipQQFBImNDW5enf60',
    appId: '1:222546543707:web:9abfd2b35df8ef17bd6b7e',
    messagingSenderId: '222546543707',
    projectId: 'retailjewelssols',
    authDomain: 'retailjewelssols.firebaseapp.com',
    storageBucket: 'retailjewelssols.appspot.com',
    measurementId: 'G-2HW33MMVFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jLTXs2khFDjtdWAH73X3LCNnDE65BTo',
    appId: '1:222546543707:android:fa0e3dbe80e8e82bbd6b7e',
    messagingSenderId: '222546543707',
    projectId: 'retailjewelssols',
    storageBucket: 'retailjewelssols.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXJKfk1d-7wxquE23kUe1W3GKvhwcsuM',
    appId: '1:222546543707:ios:48551e7c939dba3cbd6b7e',
    messagingSenderId: '222546543707',
    projectId: 'retailjewelssols',
    storageBucket: 'retailjewelssols.appspot.com',
    iosBundleId: 'com.calc.goldjewelcalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjXJKfk1d-7wxquE23kUe1W3GKvhwcsuM',
    appId: '1:222546543707:ios:bbc69cc92fa27621bd6b7e',
    messagingSenderId: '222546543707',
    projectId: 'retailjewelssols',
    storageBucket: 'retailjewelssols.appspot.com',
    iosBundleId: 'com.example.goldPricesPerCarat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgukCNEIdHXJ1CxqipQQFBImNDW5enf60',
    appId: '1:222546543707:web:6f7b5eb6498ca9a7bd6b7e',
    messagingSenderId: '222546543707',
    projectId: 'retailjewelssols',
    authDomain: 'retailjewelssols.firebaseapp.com',
    storageBucket: 'retailjewelssols.appspot.com',
    measurementId: 'G-KDFDL4E0E8',
  );
}
